### PR TITLE
Adapt to mantisBT 2.0.0

### LINKED ISSUE #3: MantisBT 2.x compatibility
Hello,

Eager to try out the CustomizeEmailSubject plug-in; however, the MantisCore requirement makes our current installation (2.5.1) ineligible:

$this->requires = array('MantisCore' => '1.2.14');

Does the plug-in need to be updated to be compatible with a MantisCore installation > 2.0.0?

Thanks,
Ryan.

### PR DESCRIPTION
**Pull request by maturbet**
To resolve https://github.com/mantisbt-plugins/CustomizeEmailSubject/issues/3

### CODE REVIEW

**Comment by maturbet** [comment]
ping @mantisbt-plugins/core-team

**Review by dregad — CHANGES_REQUESTED** [review]
Thanks for your contribution. Some adjustments are needed in config page, I get the following warnings:

>Deprecated functionality: "helper_alternate_class", use "CSS" instead. (in /home/dregad/dev/plugins/CustomizeEmailSubject/CustomizeEmailSubject/pages/config.php line 32)
Deprecated functionality: "helper_alternate_class", use "CSS" instead. (in /home/dregad/dev/plugins/CustomizeEmailSubject/CustomizeEmailSubject/pages/config.php line 41)

**Comment by maturbet** [comment]
I'm not a developer and I'm not used to using GIT.
Do you expect any further action from me ?

**Comment by dregad** [comment]
Sorry, I just did not have time to look at this yet...

**Comment by maturbet** [comment]
May be closed :
https://www.mantisbt.org/bugs/view.php?id=8986

**Pull request merged**
